Update west.yml
trying to fix the error 
FATAL ERROR: Malformed manifest file: C:\Users\seokwoo.yoon\Documents\Project4\.west\manifest-tmp\west.yml
  Schema file: c:\users\seokwoo.yoon\appdata\local\programs\python\python39\lib\site-packages\west\manifest-schema.yml
  Hint: Schema validation failed:
 - Cannot find required key 'url-base'. Path: '/remotes/3'.
 - Key 'url' was not defined. Path: '/remotes/3'.
 - Key 'revision' was not defined. Path: '/remotes/3'.